### ISSUE TITLE
One UsersDetailsEntity cannot be cast to another UsersDetailsEntity 

### ISSUE THREAD

**Issue by niyaode** [spring-projects/spring-security-oauth2-boot#140]
My parent project contains two separate SpringBoot authorization services that refer to the entity objects of the same project, both of which inherit UsersDetails. Report errors. How to specify that authorization service uses that UsersDetails object
> entities.users.UserEntity cannot be cast to entities.role.UserAdminEntity

**Comment by jzheaux** [comment]
So, the error message looks like it is specific to your project - for some reason, the application is trying to cast one of your custom domain objects to another.

This would probably be better for StackOverflow as you get access to the entire community. Would you please post your question there? It would probably also be helpful to include your existing security configuration and even a sample that demonstrates the problem.

**Comment by jzheaux** [comment]
Also, feel free to link your SO question here to the ticket.
