### ISSUE TITLE
Autoconfigure custom OAuth2RequestValidator bean

### ISSUE THREAD

**Issue by markhobson** [spring-projects/spring-security-oauth2-boot#142]
It is currently awkward to use a custom `OAuth2RequestValidator` when using the default `AuthorizationServerConfigurer`. Specifying a custom configurer to use the `AuthorizationServerEndpointsConfigurer` disables all other autoconfiguration.

Ideally any registered `OAuth2RequestValidator` bean should be configured on the `AuthorizationServerEndpointsConfigurer`.

Initially reported this under https://github.com/spring-projects/spring-boot/pull/17014 but can happily provide a PR here if of interest.

**Comment by jzheaux** [comment]
@markhobson Thanks so much for reaching out.

The ideal is that these lower-level objects be configured directly onto higher-level objects, like in this case, `TokenEndpoint` and `AuthorizationEndpoint`.

Have you already tried a custom controller?

```java
@Controller
public class EndpointsController {
    private final TokenEndpoint token;

    public EndpointsController(TokenEndpoint token, OAuth2RequestValidator validator) {
        this.token = configuration.tokenEndpoint();
        this.token.setOAuth2RequestValidator(validator);
    }

    @GetMapping("/oauth/token")
    public ResponseEntity<OAuth2AccessToken> getAccessToken(Principal principal, @RequestParam
            Map<String, String> parameters) throws HttpRequestMethodNotSupportedException {
        return this.token.getAccessToken(principal, parameters);
    }

    @PostMapping("/oauth/token")
    public ResponseEntity<OAuth2AccessToken> postAccessToken(Principal principal, @RequestParam
            Map<String, String> parameters) throws HttpRequestMethodNotSupportedException {
        return this.token.postAccessToken(principal, parameters);
    }
}
```

**Comment by markhobson** [comment]
Thanks for the reply @jzheaux. I see that this approach would be possible, if somewhat verbose. I was thinking of something along the lines of how `TokenStore` and `AccessTokenConverter` can be configured by simply registering them as beans. Would this not also make sense for `OAuth2RequestValidator`?

**Comment by jzheaux** [comment]
@markhobson yes, I agree that the solution is verbose. 

I think that something like this would also work:

```java
@Autowired
public void addRequestValidator
        (TokenEndpoint tokenEndpoint, OAuth2RequestValidator myRequestValidator) {
    tokenEndpoint.setOAuth2RequestValidator(myRequestValidator);
}
```

**Comment by jzheaux** [comment]
Would the above work for you, @markhobson? If not, let me know what makes it not ideal, and we'll see if we can come up with a better solution together.

**Comment by markhobson** [comment]
Thanks @jzheaux. I've not had a chance to try it but that could work. Note that the `AuthorizationEndpoint` would also need the request validator to be configured too.

I'm still unclear as to why `TokenStore` and `AccessTokenConverter` can be configured via bean registration but we don't wish to do the same for `OAuth2RequestValidator`? They all seem to be low-level services on par with one another.

**Comment by jzheaux** [comment]
@markhobson, fair question. The main reason is that this project is in maintenance mode, and so my inclination is to not add a feature unless it's necessary.

> Note that the AuthorizationEndpoint would also need the request validator to be configured too.

Yes, I agree.

> They all seem to be low-level services on par with one another.

I lack some of the historical context for these two components, but from my perspective, it's a matter of trying to not add too many bells and whistles. Overriding the `TokenStore` is quite common while overriding the `OAuth2RequestValidator` is not.

And, all other things being equal, this:

```java
@Bean
OAuth2RequestValidator oauth2RequestValidator() {
    return new MyRequestValidator();
}
```

is about the same complexity as:

```java
@Autowired
void addRequestValidator(AuthorizationEndpoint authorize, TokenEndpoint token) {
    OAuth2RequestValidator requestValidator = new MyRequestValidator();
    authorize.setOAuth2RequestValidator(requestValidator);
    token.setOAuth2RequestValidator(requestValidator);
}
```

Of course, if the autowired solution turns out to be flawed, let me know, and we can again take a look at this feature.

**Comment by markhobson** [comment]
No probs, thanks for your time.
