### ISSUE TITLE
OAuth2ClientContext is not accessible when handling /error v2.0

### ISSUE THREAD

**Issue by jerry-yuan** [spring-projects/spring-security-oauth2-boot#143]
Please forgive me for recreate an issue about an existed closed issue 4 month ago.
I have got the same bug like that issue(https://github.com/spring-projects/spring-security-oauth2-boot/issues/84), I appreciate that the spring official has provided a detailed disscussion about the issue and add some description on the document(https://github.com/spring-projects/spring-security-oauth2-boot/commit/1912610445fb381475544181f1c3647a2c7eeb23). Howerver after tried to add the /error to the permitAll list, I found that there still the bug in exception handling. I can even request /error without any credentials(like access_token) and get the whitelabel error page with status code 999 which is matched with the codes in BaseErrorController. But if my normal controller has throw an exception and the embed tomcat server forward the request to /error, it reproduced.
The version of Spring Cloud Greenwich.RELEASE with the spring-security-oauth2 2.3.3.RELEASE.

**Comment by jerry-yuan** [comment]
I have solved the problem by adding a RequestContextListener Bean to Spring container.
But why there missed a RequestContextListener?

**Comment by jzheaux** [comment]
@jerry-yuan I'm glad you were able to get it solved by adding a `RequestContextListener`. The request context listener is not added by default since it would assume too much about your configuration - it would be tricky for you to remove it if you didn't want it - and it's an easy thing for you to add yourself.

As for permitAll not working, will you please share a sample?

**Comment by jzheaux** [comment]
I'm closing this issue due to lack of feedback. @jerry-yuan please, of course, feel free to reopen if you feel there is more to discuss.
