### ISSUE TITLE
Backport resource server filter chain order fix

### ISSUE THREAD

**Issue by markhobson** [spring-projects/spring-security-oauth2-boot#144]
[Spring Boot 1.5 moved the OAuth2 resource filter order](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.5-Release-Notes#oauth-2-resource-filter) from `3` to `SecurityProperties.ACCESS_OVERRIDE_ORDER - 1`. This should be reflected in this project for Spring Boot 2 by backporting:

* https://github.com/spring-projects/spring-boot/issues/5072
* https://github.com/spring-projects/spring-boot/issues/8050
* https://github.com/spring-projects/spring-boot/issues/8347

**Comment by markhobson** [comment]
I've belatedly found https://github.com/spring-projects/spring-boot/issues/7958 and so I assume this is now by design. If that is indeed the case, what is the recommended approach to correctly order OAuth security filters? For example, with Spring Boot 1.5 I had:

* `AuthorizationServerConfigurerAdapter` (order = 0)
* `WebSecurityConfigurerAdapter` (order = 100)
* `ResourceServerConfigurerAdapter` (order = 2147483639)

Whereas Spring Boot 2 results in:

* `AuthorizationServerConfigurerAdapter` (order = 0)
* `ResourceServerConfigurerAdapter` (order = 3)
* `WebSecurityConfigurerAdapter` (order = 100)

Apologies if this is now more of a question rather than an issue.

**Comment by markhobson** [comment]
Furthermore, the [docs](https://docs.spring.io/spring-security-oauth2-boot/docs/current/reference/htmlsingle/#boot-features-security-oauth2-resource-server) state:

> OAuth2 resources are protected by a filter chain with order `security.oauth2.resource.filter-order` and the default is after the filter protecting the actuator endpoints by default (so actuator endpoints will stay on HTTP Basic unless you change the order).

This is true for [Spring Boot 1.5](https://github.com/spring-projects/spring-boot/blob/1.5.x/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/oauth2/resource/ResourceServerProperties.java#L184) but not for [this project](https://github.com/spring-projects/spring-security-oauth2-boot/blob/master/spring-security-oauth2-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/oauth2/resource/ResourceServerProperties.java).

**Comment by jzheaux** [comment]
@markhobson can you clarify what you are specifically struggling with?

It does sound like the documentation may need updating, but I also wonder if https://github.com/spring-projects/spring-security-oauth2-boot/blob/master/samples/spring-boot-sample-secure-oauth2-actuator/src/main/java/sample/ActuatorSecurityConfiguration.java answers your question?

**Comment by markhobson** [comment]
Hi @jzheaux, I was migrating an application:

* from Spring Boot 1.5 + Spring Security 4.2 + Spring Security OAuth 2.3
* to Spring Boot 2.1 + Spring Security 5.1 + Spring Security OAuth2 Boot 2.1

It configures an OAuth authorization server, an OAuth resource server, and a custom form login. After migration the login form was receiving a 405 `Request method 'POST' not supported` upon submission. It wasn't overly clear what was happening until I discovered the change in security filter ordering. Now the resource server was incorrectly handling the login submission.

Setting the form login security configurer to `@Order(2)`, as `spring-boot-sample-secure-oauth2-actuator` also does, does indeed fix it. Although this felt like a hack and wasn't mentioned in the docs so thought that this was an oversight. I since realise that this simplification is by design, but I would suggest either improving the OAuth + form login out-of-the-box experience somehow, or explicitly mentioning this in the docs.

**Comment by jzheaux** [comment]
> improving the OAuth + form login out-of-the-box experience

@markhobson, would you be willing to share a minimal sample of what you are trying to do with form login? I'd be happy to take a look and see what can be done to simplify, either by using existing APIs or seeing if something can be done via auto-configuration.

**Comment by jzheaux** [comment]
Documentation updated via dab82f9

**Comment by markhobson** [comment]
Hi @jzheaux, sure, here's a simple example of the problem consisting of a resource server and a custom login form:

https://github.com/markhobson/spring-security-oauth2-boot-issue

Running the test attempts to login using the custom form. Due to the new filter ordering the login POST is intercepted by the resource server which returns a 405. If you uncomment the `@Order` in `Application` to move web security before the resource server then it works as expected.
