### ISSUE TITLE
2.1.6.RELEASE not available in maven central (yet)

### ISSUE THREAD

**Issue by ttddyy** [spring-projects/spring-security-oauth2-boot#149]
Hi,

`2.1.6.RELEASE` seems to be released per github tags, but not landed on maven central.
Build/Push/Sync failure in somewhere?

**Comment by jzheaux** [comment]
Thanks, @ttddyy, it looks like Jenkins skipped the build for the release commit - I've kicked it off again, and it's now in [Maven Central](https://repo1.maven.org/maven2/org/springframework/security/oauth/boot/spring-security-oauth2-autoconfigure/2.1.6.RELEASE/).
