### ISSUE TITLE
Please don't use a `boot` suffix for the groupId

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-security-oauth2-boot#15]
Related to #2 

`boot` alone shouldn't be used in official documentation. Currently the project uses `org.springframework.security.oauth.boot`.

**Comment by rwinch** [comment]
We are GA now, so it is a bit late for that. What problems is this causing you?

**Comment by snicoll** [comment]
It is indeed too late but similar concerns have been expressed in the other issue way earlier. Unqualified use of "boot" doesn't seem legit to me but I won't fight it if not a majority shares that sentiment.
