### ISSUE TITLE
NoSuchMethodError.RedisConnection.set([B[B)V

### ISSUE THREAD

**Issue by tangdu** [spring-projects/spring-security-oauth2-boot#16]
where use 
`
Springboot 2.0.0.Release & spring-security-oauth2-autoconfigure 2.0.1.BUILD-SNAPSHOT
`
I think the problem is in lettuce

error mssaage is 
`Caused by: java.lang.NoSuchMethodError: org.springframework.data.redis.connection.RedisConnection.set([B[B)V
	at org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStore.storeAccessToken(RedisTokenStore.java:160)
	at org.springframework.security.oauth2.provider.token.DefaultTokenServices.createAccessToken(DefaultTokenServices.java:122)
	at org.springframework.security.oauth2.provider.token.AbstractTokenGranter.getAccessToken(AbstractTokenGranter.java:70)`

my code is
`
   @Autowired
    private RedisConnectionFactory redisConnectionFactory;

@Bean
    public TokenStore tokenStore() {
        RedisTokenStore redisTokenStore = new RedisTokenStore(redisConnectionFactory);
        redisTokenStore.setPrefix("user-token:");
        return redisTokenStore;
    }
`

**Comment by reith** [comment]
@tangdu did you have any progress in this?

**Comment by jgrandja** [comment]
@tangdu This has been resolved in the 2.3.2.RELEASE of `spring-security-oauth2`. See [1319](https://github.com/spring-projects/spring-security-oauth/pull/1319) and [1335](https://github.com/spring-projects/spring-security-oauth/issues/1335).

**Comment by ConnorLH** [comment]
I already excluded old bug version and add the 2.3.2.RELEASE in my project, but it still use 2.2.2 version. Somebody can help me？
``` xml
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-security</artifactId>
            <exclusions>
                <!--旧版本 redis操作有问题-->
                <exclusion>
                    <artifactId>spring-security-oauth2</artifactId>
                    <groupId>org.springframework.security.oauth</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.security.oauth</groupId>
            <artifactId>spring-security-oauth2</artifactId>
            <version>2.3.3.RELEASE</version>
        </dependency>
```

**Comment by jzheaux** [comment]
Hi, @ConnorLH, sorry you're having maven troubles. You can use `mvn dependency:tree` to see which dependency is wanting to bring in `spring-security-oauth2`.

This question is a bit better for StackOverflow, and I would recommend that you post there to get additional support.
