### ISSUE TITLE
I can't use OAuth2AutoConfiguration with webflux.pluse help me .

### ISSUE THREAD

**Issue by flowclouds** [spring-projects/spring-security-oauth2-boot#168]
I see the OAuth2AutoConfiguration.java autoconfig annation @AutoConfigureBefore(WebMvcAutoConfiguration.class) .
must it means start with springMVC? How can I start with webflux?

this is my denpendce

dependencies {
    compile 'org.springframework.boot:spring-boot-starter-security'
    compile 'org.springframework.cloud:spring-cloud-starter-gateway'
    compile 'mysql:mysql-connector-java'
    compile "io.springfox:springfox-swagger2:3.0.0-SNAPSHOT"
    compile "io.springfox:springfox-spring-webflux:3.0.0-SNAPSHOT"
   compile  'org.springframework.security.oauth.boot:spring-security-oauth2-autoconfigure'
}

i want use @EnableOAuth2Sso but it run with error and print 
Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2SsoDefaultConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.security.config.annotation.ObjectPostProcessor<?>' available

Description:

A component required a bean of type 'org.springframework.security.config.annotation.ObjectPostProcessor' that could not be found.

Action:

Consider defining a bean of type 'org.springframework.security.config.annotation.ObjectPostProcessor' in your configuration.

**Comment by jzheaux** [comment]
And actually for the majority of OAuth 2.0 use cases, I'd recommend Spring Security instead of this project, not just for reactive applications.
