### ISSUE TITLE
Use serviceId to fetch JWT public key

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [spring-projects/spring-security-oauth2-boot#17]
Hi there!

In order to fetch the public key from the Authorization Server, we have to use `security.oauth2.resource.jwt.key-uri` in the Resource Server to set where the Authorization Server is. Since this URI can change based on which environment the Resource Server is running (development, staging, production), wouldn't be nice if the Resource Server could find the Authorization Server using it's ID registered in Eureka?

This would bring cloud dependencies to this project, and I would like to know if there is a problem doing so. If there is no problem, I can develop and PR this feature.

This way the resource server could have a property like this:
`security.oauth2.resource.jwt.key-service-id=my-auth-server`

If this property is set, and if the app is registered in Eureka, then oauth2-boot will ask Eureka for the `my-auth-server` instance to fetch the JWT public key.

Best regards,
Rafael Pacheco.

**Comment by jgrandja** [comment]
@rafaelrenanpacheco We would not want to introduce a Spring Cloud dependency to the project. Also, it seems that this feature would make more sense in one of the Spring Cloud sub-projects, possibly Spring Cloud Security?

In case you are not already aware, we are limiting new features to Spring Security OAuth as well as this project given the new direction for OAuth 2.0 support currently underway in Spring Security 5. Please see this [blog](https://spring.io/blog/2018/01/30/next-generation-oauth-2-0-support-with-spring-security) for more details.

**Comment by rafaelrenanpacheco** [comment]
@jgrandja thanks for the feedback! Good to know that OAuth2 is getting a better support. And I did ask myself the **Which project(s) do I use** question few days ago :smiley: 

Best regards,
Rafael Pacheco.

**Comment by jgrandja** [comment]
@rafaelrenanpacheco No worries. We're targeting initial Resource Server support for 5.1. After the release, we can look at potentially adding this feature to one of the Spring Cloud projects at that time. Please keep an eye out as things progress forward. Thanks!
