### ISSUE TITLE
bean 'oauth2ClientContext' duplicated

### ISSUE THREAD

**Issue by loki8217** [spring-projects/spring-security-oauth2-boot#179]
i am a newbie in oauth2 , i find there is a issue when i want to implement credential grant type client. 

log as below:

The bean 'oauth2ClientContext', defined in class path resource [org/springframework/boot/autoconfigure/security/oauth2/client/OAuth2RestOperationsConfiguration$SingletonScopedConfiguration.class], could not be registered. A bean with that name has already been defined in BeanDefinition defined in class path resource [org/springframework/security/oauth2/config/annotation/web/configuration/OAuth2ClientConfiguration$OAuth2ClientContextConfiguration.class] and overriding is disabled.

Action:
Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

[TestForOauth2.zip](https://github.com/spring-projects/spring-security-oauth2-boot/files/3823151/TestForOauth2.zip)

The sample code is very simple, i think this issue can be reproduced very easy.
when you set grant type =  client_credentials, it will trying to registry another oauth2ClientContext bean which is already there.

I know i can set overriding=true to avoid this exception. But i want to avoid to do that if possible, I am afraid bean overriding will produce other issues in future.
I think it is not so hard to just add a @ConditionalOnMissingBean there.
And finally i have to say i am not very confident that it is a issue, because i am new to use oauth2, maybe there is some inappropriate usages in my code. Please feel free to commit on this issue at any time. 
thank you.

**Comment by jzheaux** [comment]
@loki8217 sorry to hear you are having trouble.

Have you already checked https://github.com/spring-projects/spring-security-oauth2-boot/issues/85#issuecomment-464084127 and https://github.com/spring-projects/spring-security-oauth2-boot/issues/51#issuecomment-428252825 to see if they address your issue?

**Comment by jzheaux** [comment]
@loki8217 I haven't heard back from you on my question. 

If I still haven't heard from you by the end of the week, I'll close this ticket due to inactivity.

**Comment by loki8217** [comment]
> @loki8217 I haven't heard back from you on my question.
> 
> If I still haven't heard from you by the end of the week, I'll close this ticket due to inactivity.

I am sorry for my late response. I used some time to do research work on oauth2. This issue is caused by my inappropriate usage. It don't make any senses to use both enableOauthClient and client credential grant type.
Thank you very much.
