### ISSUE TITLE
Enhancement: auto configure with JWT keystore

### ISSUE THREAD

**Issue by power721** [spring-projects/spring-security-oauth2-boot#18]
For a simple web app, I want to enable Authorization Server and Resource Server at the same time.
I just want to add a JWT keystore with properties, so everything will work.
I don't dependent on external server or more configuration.

Sample application.yml:
```security:
  oauth2:
    authorization:
      jwt:
        key-store: classpath:jwt.jks
        password: changeme
        alias:  jwt
```

Reference implemenation:
```

@Configuration
@ConditionalOnClass(EnableAuthorizationServer.class)
@Conditional(OAuth2JwtKeyStoreConfiguration.JwtKeyStoreCondition.class)
@EnableConfigurationProperties(AuthorizationServerJwtProperties.class)
public class OAuth2JwtKeyStoreConfiguration {

    private final ApplicationContext context;
    private final AuthorizationServerJwtProperties properties;

    @Autowired
    public OAuth2JwtKeyStoreConfiguration(AuthorizationServerJwtProperties properties, ApplicationContext context) {
        this.context = context;
        this.properties = properties;
    }

    @Bean
    @ConditionalOnMissingBean(TokenStore.class)
    public TokenStore tokenStore() {
        return new JwtTokenStore(accessTokenConverter());
    }

    @Bean
    @ConditionalOnMissingBean(AccessTokenConverter.class)
    public JwtAccessTokenConverter accessTokenConverter() {
        JwtAccessTokenConverter converter = new JwtAccessTokenConverter();
        KeyStoreKeyFactory keyStoreKeyFactory = new KeyStoreKeyFactory(context.getResource(properties.getKeyStore()),
            properties.getPassword().toCharArray());
        converter.setKeyPair(keyStoreKeyFactory.getKeyPair(properties.getAlias()));
        return converter;
    }

    public static class JwtKeyStoreCondition extends SpringBootCondition {

        @Override
        public ConditionOutcome getMatchOutcome(ConditionContext context, AnnotatedTypeMetadata metadata) {
            ConditionMessage.Builder message = ConditionMessage.forCondition("OAuth JWT keystore Condition");
            AuthorizationServerJwtProperties jwt = Binder.get(context.getEnvironment())
                .bind("security.oauth2.authorization.jwt", AuthorizationServerJwtProperties.class).orElse(null);
            if (jwt != null) {
                String keyStore = jwt.getKeyStore();
                String password = jwt.getPassword();
                String alias = jwt.getAlias();
                if (StringUtils.hasText(keyStore) && StringUtils.hasText(password) && StringUtils.hasText(alias)) {
                    return ConditionOutcome.match(message.foundExactly("provided jwt key store"));
                }
            }
            return ConditionOutcome.noMatch(message.didNotFind("provided jwt key store").atAll());
        }
    }

}

```

**Comment by jgrandja** [comment]
@power721 As an FYI, please see this recent [announcement](https://spring.io/blog/2018/01/30/next-generation-oauth-2-0-support-with-spring-security).

As indicated in the announcement, [Spring Security OAuth](https://projects.spring.io/spring-security-oauth/) is officially in maintenance mode. We will provide bug/security fixes and consider adding minor features but we will not be adding major features. This project is closely associated to Spring Security OAuth so the same maintenance plan applies.

However, given this feature request is considered minor, we would consider adding it.

Would you be interested in submitting a PR for this? Looks like you've already started the work?

**Comment by power721** [comment]
Yes.
I had used this patch in spring-boot 1.5 for a while.
Just migrate the RelaxedPropertyResolver to Binder API for spring-boot 2.0.

**Comment by punkstarman** [comment]
What about configuring the JWT signing key directly? For instance, through the `security.oauth2.resource.jwt.key-value` configuration.

BTW, I find it strange that on resource servers, `ResourceServerTokenServicesConfiguration` supplies autoconfigured `JwtTokenStore` and `JwtAccessTokenConverter`, but there is no equivalent for authorization servers.
