### ISSUE TITLE
Oauth2 Boot reference document' example miss a “{”

### ISSUE THREAD

**Issue by kioyong** [spring-projects/spring-security-oauth2-boot#185]
https://docs.spring.io/spring-security-oauth2-boot/docs/current-SNAPSHOT/reference/htmlsingle/#accessing-a-resource

the example is :
```java
@RestController
public class SimpleController
	@GetMapping("/whoami")
	public String whoami(@AuthenticationPrincipal(expression="name") String name) {
		return name;
    }
}
```
expect result :
```java
@RestController
public class SimpleController {
	@GetMapping("/whoami")
	public String whoami(@AuthenticationPrincipal(expression="name") String name) {
		return name;
    }
}
```

sorry I don't know if the documentation issue should be submitted here or not.

**Comment by jzheaux** [comment]
@kioyong thanks for the report. Yes, this is a good place to report those kinds of issues.

Would you be interested in submitting a PR to fix the documentation?

**Comment by kioyong** [comment]
i careated a PR to fix the documentation, refer:
https://github.com/spring-projects/spring-security-oauth2-boot/pull/187
