### ISSUE TITLE
Release cycle same as in Spring Boot project

### ISSUE THREAD

**Issue by mkopylec** [spring-projects/spring-security-oauth2-boot#19]
It would be nice to have all the dependencies updated to versions as in Spring Boot.
Now SB is 2.0.1.RELEASE and has newer dependencies than this starter which is 2.0.0.RELEASE.

**Comment by DanielFran** [comment]
@jzheaux It would be nice also to have a branch that align with 2.1.0.M2.

**Comment by jzheaux** [comment]
@DanielFran We will do a 2.1.0.M2 release on August 28th.

**Comment by jzheaux** [comment]
Closing since we now have milestones configured and scheduled for [each of the boot releases](https://github.com/spring-projects/spring-security-oauth2-boot/milestones).
