### ISSUE TITLE
使用security.oauth2.resource.user-info-uri时无法校验resourceId

### ISSUE THREAD

**Issue by 5u5u** [spring-projects/spring-security-oauth2-boot#202]
正常逻辑每次请求会在`org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationManager#authenticate` 校验resourceIds，

不包含时抛出`throw new OAuth2AccessDeniedException("Invalid token does not contain resource id (" + resourceId + ")");`  

但是如果配置的是`security.oauth2.resource.user-info-uri`默认会使用`org.springframework.boot.autoconfigure.security.oauth2.resource.UserInfoTokenServices`

这个类里面`resourceIds`一直是null，这样导致资源服务器就算设置了resourceId也不会去校验
![image](https://github-production-user-asset-6210df.s3.amazonaws.com/32949827/71581303-78551f80-2b3f-11ea-85b0-6baf226688ab.png)

**Comment by jzheaux** [comment]
@synchronizeds would you be able to explain your problem in English? Or, could you post to GitHub a minimal sample with a test that demonstrates the issue you are experiencing?

**Comment by synchronizeds** [comment]
The normal logic will verify the resourceids at `org.springframework.security.oauth2.provider.authentication.oauth2authenticationmanager` every time it requests,
`Throw throw new oauth2accessdeniedexception ("invalid token does not contain resource ID (" + resourceid + ")");`

But if `security.oauth2.resource.user-info-uri` is configured, `org.springframework.boot.autoconfigure.security.oauth2.resource.userinfotoken` services will be used by default

The resourceids in this class are always null, which causes the resource server not to verify even if the resourceid is set

**Comment by jzheaux** [comment]
Thanks for the report, @5u5u. I think it makes sense to add a `UserInfoTokenServices#setResourceId` method.

Would you be interested in submitting a PR?

**Comment by jzheaux** [comment]
Due to the lack of feedback on this ticket, I'm going to close it. Feel free to reopen if you feel like there is more to discuss.
