### ISSUE TITLE
Missing tag and artifacts for spring boot 2.2.4.RELEASE

### ISSUE THREAD

**Issue by tomfi** [spring-projects/spring-security-oauth2-boot#209]
While upgrading to latest available spring boot version (2.2.4.RELEASE) i got a compilation error that `spring-security-oauth2-autoconfigure` version 2.2.4.RELEASE does not exist.

Checking maven central, it seems like it really does not exist: https://mvnrepository.com/artifact/org.springframework.security.oauth.boot/spring-security-oauth2-autoconfigure

Checking this repository, i see there is no tag for `2.2.4.RELEASE`.

Is it intentional, should i manage this version manually in my bom?

Thanks in advance.

**Comment by tomfi** [comment]
Seems like it was my bad, it is managed internally and i had a module that used **spring-boot-version** instead of the internal managed version which caused the issue.

Closing this issue.

**Comment by jzheaux** [comment]
Glad you found the issue, @tomfi! Don't hesitate to reach out if you have further concerns.
