### ISSUE TITLE
client with access token/refresh token -- is it implemented?

### ISSUE THREAD

**Issue by 2019-05-10** [spring-projects/spring-security-oauth2-boot#225]
I need to create an OAuth2 client that uses access token and refresh token to frequently downloads data from the server.
1) The server is 3d party service I have no control over
2) authentication has already be done and I am handed the access token and refresh token
3) with those two I need to collect once a day data, hence refresh the token every 24hrs, store and use it for my requests

After several days I am no longer sure this is possible with spring security oauth2 -- documentation is rather confusing and all examples, be it with Spring or elsewhere concentrate on a server (which I don't need) or stop with authorization/password login.

So, is my scenario at all possible with this project or do I need to do everything on my own?
If this _is_, in fact, answered somewhere, could you please point me to that?

If, as I suspect, this neither possible nor has been stated somewhere, please, add clear information about that in the docs.

**Comment by jzheaux** [comment]
Hi, @2019-05-10, thanks for reaching out.

I'd recommend that you take a look at [Spring Security's built-in OAuth 2.0 Client support](https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#oauth2client). There, you'll find [`WebClient` support](https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#oauth2Client-webclient-servlet) that will perform the refresh token update for you.
