### ISSUE TITLE
set user-info-uri programmatically

### ISSUE THREAD

**Issue by jmart1** [spring-projects/spring-security-oauth2-boot#23]
Through the use of the OAuth2RestTemplate class, we have been able to programmatically configure our resource servers.  We configure clientId, clientSecret, accessTokenUri, and userAuthorizationUri directly on to the OAuth2RestTemplate.  

The remaining configuration that we are still setting in our application.yml file is userInfoUri (security.oauth2.resource.userInfoUri to be exact).  Would it be possible to set this field programmatically also?

The reason for the need for this is that we are centralizing many of our env and secret properties.  In this case we originally wanted to just centralize (and secure) the clientSecret and clientId.  We store this info in AWS Secrets Manager and configure the OAuth2RestTemplate in the code to use the values from the AWS Secrets Manager.  We extended this to store almost all the OAuth2 properties, except for userInfoUri... which shows up multiple times in our applications.yml (once per each environment).

**Comment by jgrandja** [comment]
@jmart1 `OAuth2RestTemplate` is associated with a `OAuth2ProtectedResourceDetails` so the only way at the moment is to extend one of the `OAuth2ProtectedResourceDetails` (for example, `AuthorizationCodeResourceDetails`) and provide a `userInfoUri` attribute. However, to make this useful, `OAuth2RestTemplate` would need to leverage this new attribute as well which make things a little more complicated. So there is no easy way to make this work out of the box.

Also, as an FYI, we're not looking to add any new features to the `spring-security-oauth2` project as it's in maintenance mode and our efforts are focused in the new OAuth support we're building in Spring Security 5. See this [blog](https://spring.io/blog/2018/01/30/next-generation-oauth-2-0-support-with-spring-security) for more details.

I'm going to close this issue as I feel I have answered your question. If I haven't, I'll re-open it to continue the discussion.
