### ISSUE TITLE
override AuthorizationCodeResourceDetails 

### ISSUE THREAD

**Issue by heyunit** [spring-projects/spring-security-oauth2-boot#25]
I tried to extend the AuthorizationCodeResourceDetails but am running into the following issue.

In the OAuth2ProtectedResourceDetailsConfiguration class in the org.springframework.boot.autoconfigure.security.oauth2.client package the AuthorizationCodeResourceDetails bean is annotated w/ @primary.

Furthermore, the OAuth2ProtectedResourceDetailsConfiguration is not a public class meaning it can't be excluded from the component scan.

And in the OAuth2RestOperationsConfiguration only support ClientCredentials. I want to use password

Last in the DefaultUserInfoRestTemplateFactory I had no idea how to do it,

**Comment by jgrandja** [comment]
@InfiniteJust1ce Have you tried using `@Qualifier`?

For example, if you define this `@Bean`:

```
	@Bean
	@ConfigurationProperties(prefix = "security.oauth2.client")
	@Qualifier("customAuthorizationCodeResourceDetails")
	public AuthorizationCodeResourceDetails customAuthorizationCodeResourceDetails() {
		// OR return your extended version of AuthorizationCodeResourceDetails
		return new AuthorizationCodeResourceDetails();
	}
```

Then you can inject it as follows:

```
	@Autowired
	@Qualifier("customAuthorizationCodeResourceDetails")
	private AuthorizationCodeResourceDetails customAuthorizationCodeResourceDetails;
```

**Comment by jzheaux** [comment]
@heyunit, just curious, did @jgrandja's suggestion work for you?

**Comment by jzheaux** [comment]
Closing this, though @heyunit feel free to reopen if @jgrandja's suggestion didn't work.
