### ISSUE TITLE
OAuth2ClientProperties was moved and conflicts with Spring Boot provided class

### ISSUE THREAD

**Issue by andrei-ivanov** [spring-projects/spring-security-oauth2-boot#251]
Trying to upgrade to 2.3.0 I get this error:
```
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-maven) @ resource-server ---
[WARNING] Rule 2: org.apache.maven.plugins.enforcer.BanDuplicateClasses failed with message:
Duplicate classes found:

  Found in:
    org.springframework.boot:spring-boot-autoconfigure:jar:2.3.0.RELEASE:compile
    org.springframework.security.oauth.boot:spring-security-oauth2-autoconfigure:jar:2.3.0.RELEASE:compile
  Duplicate classes:
    org/springframework/boot/autoconfigure/security/oauth2/client/OAuth2ClientProperties.class
```

As far as I see, until 2.3.0, `OAuth2ClientProperties` was in a different package, `org.springframework.boot.autoconfigure.security.oauth2`, so it didn't conflict with the one provided by Spring Boot, but then it was moved in 6a312d2.

Any chance of reverting this change?

I'm stuck with the old OAuth2 classes since I have an Authorization Server built on it and the new Spring Security doesn't provide one.

**Comment by andrei-ivanov** [comment]
ping

**Comment by jzheaux** [comment]
Sorry for the delay, @andrei-ivanov. This is still on my radar for the `2.3.1.RELEASE`.

**Comment by jzheaux** [comment]
I think reverting is an option, @andrei-ivanov, but reverting will re-introduce the package cycle that moving it solved. Before reverting, then, I'd like to see if there's another home for `OAuth2ClientProperties` that still resolves the package cycle.

Would you be able to produce a minimal sample (in a separate GitHub project) that uses the Maven Enforcer Plugin? I could use that to test against an make sure whatever change is made doesn't cause further problems.

**Comment by blacelle** [comment]
https://github.com/solven-eu/spring-security-oauth2-boot_251/

Hope it helps. We also hoped this for `2.3.1.RELEASE`

**Comment by blacelle** [comment]
In which release will this be integrated ? Thanks

Le lun. 15 juin 2020 à 20:49, Josh Cummings <notifications@github.com> a
écrit :

**Comment by jzheaux** [comment]
This is targeted for the `2.3.1` release. You can check this in the future on the right-hand side of the issue under the `Milestones` heading.
