### ISSUE TITLE
map out an authority that's not in the jwt token, but in the userinfo response

### ISSUE THREAD

**Issue by jmoseman01** [spring-projects/spring-security-oauth2-boot#259]
Question

I've been looking for the answer to this for awhile, can you guys please help me?

https://stackoverflow.com/questions/62586995/how-do-you-assign-a-role-when-its-in-userinfo-and-not-the-jwt-claims-in-spring

I'm trying to map out an authority that's not in the jwt token, but in the userinfo response.  Do you guys know how to do that?

**Comment by jzheaux** [comment]
@jmoseman01, I'm guessing that you found a satisfactory answer? I'm asking since it appears that the SO question has no accepted answer.

**Comment by jmoseman01** [comment]
I'm just using a REST template to call it with the token that I got.
