### ISSUE TITLE
Update spring-security-oauth2 to 2.3.3.RELEASE

### ISSUE THREAD

**Issue by MadeInChina** [spring-projects/spring-security-oauth2-boot#27]
Which fixed NoSuchMethodError.RedisConnection.set([B[B)V issue
 
>refer to https://github.com/spring-projects/spring-security-oauth2-boot/issues/16

**Comment by larsduelfer** [comment]
Is there any date yet when 2.1.0 will be released? I require a change in spring-security-oauth2 that allows a custom return type in WebResponseExceptionTranslator.translate(...). Otherwise you are stuck with the OAuth2Exceptions. Would be great to have that soon. Thanks in advance for a response!

**Comment by jgrandja** [comment]
@larsduelfer You can always override the pulled in version by explicitly overriding the version in your gradle build, for example:

`dependency  org.springframework.security.oauth:spring-security-oauth2:2.3.3.RELEASE`
