### ISSUE TITLE
Documentation for CustomAuthorizationServerConfigurer

### ISSUE THREAD

**Issue by PhazedOut** [spring-projects/spring-security-oauth2-boot#29]
The CustomAuthorizationServerConfigurer in the documentation does not work because the password grant type is disabled when the auto configuration is turned off (AuthenticationManager is no longer provided). The documentation should show AuthenticationManager being injected into AuthorizationServerEndpointsConfigurer:

    @Configuration
    @EnableAuthorizationServer
    public class CustomAuthorizationServerConfigurer extends AuthorizationServerConfigurerAdapter {

    private final AuthenticationManager authenticationManager;

    public CustomAuthorizationServerConfigurer(AuthenticationConfiguration authenticationConfiguration) throws Exception {
        this.authenticationManager = authenticationConfiguration.getAuthenticationManager();
    }

    @Override
    public void configure(ClientDetailsServiceConfigurer clients) throws Exception{
        clients.inMemory()
                .withClient("client")
                .authorizedGrantTypes("password")
                .secret("{noop}secret")
                .scopes("all");
    }

    @Override
    public void configure(AuthorizationServerEndpointsConfigurer endpoints) throws Exception {
        endpoints.authenticationManager(authenticationManager);
    }
}

**Comment by jzheaux** [comment]
Thanks for the report, @PhazedOut. I'll add more detail to the documentation.
