### ISSUE TITLE
Version 2.4.8 and 2.5.2 were not published

### ISSUE THREAD

**Issue by oliverlockwood** [spring-projects/spring-security-oauth2-boot#333]
Look at https://mvnrepository.com/artifact/org.springframework.security.oauth.boot/spring-security-oauth2-autoconfigure

![Screenshot 2021-07-05 at 14 55 51](https://user-images.githubusercontent.com/6017680/124482383-1f53f080-dda1-11eb-8a88-e583d6ea0b9a.png)

As I understand it, although yes this artefact is deprecated, it's continuing to be released alongside Spring-Boot, i.e. the versions https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-dependencies

![Screenshot 2021-07-05 at 14 56 55](https://user-images.githubusercontent.com/6017680/124482508-43173680-dda1-11eb-8bd1-d2abe55322e3.png)

It seems pretty self-evident that version 2.4.8 and 2.5.2 is missing.  Can you please fix this, or explain where I'm misunderstanding?

**Comment by jzheaux** [comment]
Closed in e27fdfaad6b9773b308bc3c55e2261f0cab2e270 and 235d103e66a0750c55d839848dc6ea619ba78f1b

**Comment by oliverlockwood** [comment]
Thank you @jzheaux for resolving this promptly.
