### ISSUE TITLE
Version 2.5.7 was not published

### ISSUE THREAD

**Issue by oliverlockwood** [spring-projects/spring-security-oauth2-boot#355]
Identical to issue #333, except the version that's missing is 2.5.7.

Perhaps @jzheaux you can resolve this, also?

Many thanks!

**Comment by jzheaux** [comment]
Done! https://github.com/spring-projects/spring-security-oauth2-boot/releases/tag/2.5.7

**Comment by oliverlockwood** [comment]
Thanks again @jzheaux for the early Christmas present! 🎅
