### ISSUE TITLE
Release a milestone build using Spring Boot 3

### ISSUE THREAD

**Issue by Thihup** [spring-projects/spring-security-oauth2-boot#363]
Hi there!

Do you think it would be possible to release a milestone/snapshot build of this project using Spring Boot 3?

**Comment by jzheaux** [comment]
Hi, @Thihup, there are no plans to release this for Spring Boot 3 as per https://spring.io/blog/2021/11/08/update-on-eol-for-spring-security-oauth

Please consider [migrating to Spring Security](https://github.com/spring-projects/spring-security/wiki/OAuth-2.0-Migration-Guide).
