### ISSUE TITLE
Update to Spring Boot 2.6.4

### ISSUE THREAD

**Issue by nburles** [spring-projects/spring-security-oauth2-boot#369]
[PR attached](https://github.com/spring-projects/spring-security-oauth2-boot/pull/370)

**Comment by oliverlockwood** [comment]
Yes please, @jzheaux or another maintainer, would you please review and get this built?  Many thanks.

**Comment by jzheaux** [comment]
Closed in 1bb69ea050eb716d1e508a1389e1051c5c54df38
