### ISSUE TITLE
When will the new version of spring-security-oauth2-autoconfigure be released?

### ISSUE THREAD

**Issue by FerTDuarte** [spring-projects/spring-security-oauth2-boot#381]
Hi,

Will we have the new version (6.2.7) of 'spring-security-oauth2-autoconfigure' soon?

**Comment by CharliePrm88** [comment]
I am waiting too. And please upgrade also other dependecy as requested from [this](https://github.com/spring-projects/spring-security-oauth2-boot/pull/379)

**Comment by jzheaux** [comment]
My apologies for the delay. [2.6.7](https://github.com/spring-projects/spring-security-oauth2-boot/releases/tag/2.6.7) is just released and should be in Maven Central soon.
