### ISSUE TITLE
spring-security-oauth2-boot 2.7.0

### ISSUE THREAD

**Issue by anbusampath** [spring-projects/spring-security-oauth2-boot#388]
Will there be spring-security-oauth2-boot 2.7.0 release? Because multiple milestone released to align with Spring Boot 2.7 and currently project marked EOL(https://github.com/spring-projects/spring-security-oauth2-boot/commit/bf509aeec07a9411c4e4fa95c645c9119ad9a584).

https://github.com/spring-projects/spring-security-oauth2-boot/releases/tag/2.7.0-M3
https://github.com/spring-projects/spring-security-oauth2-boot/releases/tag/2.7.0-M2
https://github.com/spring-projects/spring-security-oauth2-boot/releases/tag/2.7.0-M1

It would be great to have 2.7.0 as last release to align with Spring Boot.

**Comment by jgrandja** [comment]
@anbusampath No, there will not be a 2.7.0 release. This project has reached EOL.
