### ISSUE TITLE
AuthorizationServer endpoints are overriden(?) by my RequestMappings

### ISSUE THREAD

**Issue by vitalyster** [spring-projects/spring-security-oauth2-boot#46]
Here is the [demo project](https://github.com/vitalyster/oauth-demo) - I want to have mvc urls protected with form login and api urls protected with authorization and resource server in the same application.
Everything works as [expected](https://github.com/vitalyster/oauth-demo/commit/edfbb30dc95b264506b8e0e939bfd0f20e1d024c) with the help of autoconfig until I [add new GET mapping](https://github.com/vitalyster/oauth-demo/commit/1c2e609c7a682a06be8a378c7120e388f3d98a70) and it somehow breaks `/oauth/token` POST(!) endpoint. What's wrong in my configuration?

**Comment by jzheaux** [comment]
@vitalyster While it may seem surprising, what Spring MVC is doing is seeing the request for /oauth/token and matching it to the pattern "/{user}/{messageId}". Then, seeing that it is only mapped to GET, responds with a 405 (Method Not Supported).

There may be a way to convince Spring MVC to not match `/oauth/token` to that endpoint, though I would defer to the MVC folks for supporting you in that regard.

As you probably already know, if I change the mapping to `@GetMapping("/{user}/message/{messageId}")` then the test passes. Is there a particular reason that you wouldn't be able to adjust the uri in a similar fashion?

**Comment by vitalyster** [comment]
I already have production application with `/{user}/{messageid}` mapping and there are a lot of logic depended on it and it need much time to adjust it, while I just want to quickly add some oauth endpoints. I think it's possible to adjust oauth endpoints (maybe with prefix?) but did not find clear way for it too.

**Comment by vitalyster** [comment]
Solved the issue by copying `OAuth2AuthorizationServerConfiguration` to my project and adding prefixes with `pathMapping`. Autoconfiguration correctly pick up my config and everything other works autoconfigured :) The right way is to externalize  path mappings properties but as this project in maintenance state I think nobody will care :)
