### ISSUE TITLE
Update spring-boot version to 2.1.0-RC1

### ISSUE THREAD

**Issue by DanielFran** [spring-projects/spring-security-oauth2-boot#54]

**Comment by DanielFran** [comment]
@jzheaux I do not see the 2.1.0.RC1 available in maven repository. Can you please confirm if the release process was ok?
Thanks

**Comment by jzheaux** [comment]
@DanielFran thanks for checking.

We moved the release to [Monday](https://github.com/spring-projects/spring-security-oauth2-boot/milestone/12) to give some extra time on an issue that we didn't want to push past RC1. You should see it in maven on Monday.
