### ISSUE TITLE
Add spring-configuration-metadata.json 

### ISSUE THREAD

**Issue by nealeu** [spring-projects/spring-security-oauth2-boot#6]
Hi,

I'm doing my first Spring Boot 2 app, and everything I'd expect to work with auto-completion for properties is working ... apart from the security bits.

I get prompted with all the deprecated properties, but not the actual ones.

Looking at the jars, I can see additional-spring-configuration-metadata.json, but not spring-configuration-metadata.json, as is present in other Spring Boot components

**Comment by rwinch** [comment]
@nealeu Thanks for the report! This is now fixed in master

**Comment by nealeu** [comment]
Thanks for the fast turnaround :+1:
