### ISSUE TITLE
Automate JDK CI upgrades using AdoptOpenJDK API

### ISSUE THREAD

**Issue by DanielFran** [spring-projects/spring-security-oauth2-boot#73]
@jzheaux Might be of some interest: https://github.com/spring-projects/spring-boot/issues/15164

**Comment by DanielFran** [comment]
@jzheaux You can close it if you want...

**Comment by jzheaux** [comment]
Hey @DanielFran! I always appreciate your input. I'll be taking a look at this ticket this week.

**Comment by jzheaux** [comment]
@DanielFran Thank you for the great idea, but it's not applicable right now since Spring Security doesn't control the shared environment that it is built within.
