### ISSUE TITLE
401 appears when /login of client server is returned after the authorization server is successfully authorized.

### ISSUE THREAD

**Issue by niyaode** [spring-projects/spring-security-oauth2-boot#86]
**If the client does not login, it redirects to the authorization server to request authorization. 401 appears in the client /login path after the authorization is successfully returned.**
I submitted a simple sample on [github](https://github.com/niyaode/OAuthSSO)
**Versions of relevant Spring packages used:**

* spring-framework: 5.1.3.RELEASE
* spring-security-oauth2-autoconfigure: 2.1.2.RELEASE
* spring-boot-starter-web: 2.1.2.RELEASE
* spring-security-oauth2: 2.3.4.RELEASE

![tim 20190214083112](https://user-images.githubusercontent.com/27875141/52755517-2f849d00-3039-11e9-8515-9df0eb7402e1.png)
![tim 20190214083124](https://user-images.githubusercontent.com/27875141/52755518-301d3380-3039-11e9-8327-96c88a11c75d.png)
![tim 20190214083132](https://user-images.githubusercontent.com/27875141/52755519-301d3380-3039-11e9-9d60-1cb778c32ddf.png)

**Comment by jzheaux** [comment]
Thanks, @niyaode, for the example, I'll take a look and get back to you shortly.

**Comment by jzheaux** [comment]
It appears that two things are happening here. First, you might be affected by #70, and I would recommend using the latest version (2.1.2.RELEASE) at this point:

```diff
<dependency>
            <groupId>org.springframework.security.oauth.boot</groupId>
            <artifactId>spring-security-oauth2-autoconfigure</artifactId>
-            <version>2.1.0.RELEASE</version>
+            <version>2.1.2.RELEASE</version>
</dependency>
```

Second, the `client-authentication-scheme` property is there to state how the client application should authenticate itself to the authorization server, say to the `/oauth/token` endpoint. The `form` setting is for authorization servers that require that authentication be form-based like with GitHub. The Spring Security authorization server doesn't need that, so you can remove it:

```diff
...
userAuthorizationUri: http://idp.endpoint:9999/oauth/authorize
- client-authentication-scheme: form
scope: [all]
...
```

The 401 you are getting is the 401 from the authorization server, stating that it couldn't authenticate the client for the `/oauth/token` request.

Let me know if these two changes work for you.

**Comment by jzheaux** [comment]
@niyaode mentioned in #70 that this addressed his issue. Please feel free to re-open if there is more to discuss.
